### ISSUE TITLE
Runs successfully but empty output file

### ISSUE THREAD

**Issue by skudashev** [alejandrogzi/gtfsort#13]
Hello, 

Thank you for your tool. I've tried running gtf sort with `gtfsort --input $in_gtf --output $out_gtf --threads 8` and got this log out, but the output file is empty. 

```
Version: 0.2.2
2024-10-28T10:22:20.386Z INFO  [gtfsort] Using 8 threads
2024-10-28T10:22:22.739Z INFO  [gtfsort] Elapsed time: 2.3530 seconds
2024-10-28T10:22:22.739Z INFO  [gtfsort] Memory usage: 3053.0000 MB
2024-10-28T10:22:23.678Z INFO  [gtfsort] Success: GTF file sorted successfully!
```
Your tool would be very useful if it works.

Best,
Sofia

**Comment by alejandrogzi** [comment]
Hi @skudashev 

Could you please share your input? I will try to replicate it here and see what's going on.

Thanks,
Alejandro

**Comment by skudashev** [comment]
[test.gtf.gz](https://github.com/user-attachments/files/17541490/test.gtf.gz)

**Comment by skudashev** [comment]
Hi, 
I've added the top 20 lines of my gtf file. Hope this helps.
Sofia

**Comment by alejandrogzi** [comment]
Hey,

Thanks. I just looked at it. Could you please include lines with 'gene' and 'transcript' keywords (just grepping random gene names and sending the whole output to a file). Right now, all of them are just 'exon', which will not produce anything because gtfsort needs to build a tree based on these keywords.

Thanks,
Alejandro

**Comment by skudashev** [comment]
Ah I see, I think the issue here was that this particular tool outputs GTF files that only contain exon coordinates, I tested your tool on a different gtf and it worked fine. Thanks for clearing that up.

**Comment by ElizabethWallace97** [comment]
I have this issue with a file that has more than just exon coordinates. Here is the head of my file:

> chr1	ncbiRefSeq	transcript	381594	384673	.	-	.	gene_id "LOC100387375"; transcript_id "XR_004740434.1";  gene_name "LOC100387375";
> chr1	ncbiRefSeq	exon	381594	384673	.	-	.	gene_id "LOC100387375"; transcript_id "XR_004740434.1"; exon_number "1"; exon_id "XR_004740434.1.1"; gene_name "LOC100387375";
> chr1	ncbiRefSeq	transcript	386828	428463	.	-	.	gene_id "LOC118152095"; transcript_id "XR_004740445.1";  gene_name "LOC118152095";
> chr1	ncbiRefSeq	exon	386828	388600	.	-	.	gene_id "LOC118152095"; transcript_id "XR_004740445.1"; exon_number "3"; exon_id "XR_004740445.1.3"; gene_name "LOC118152095";
> chr1	ncbiRefSeq	exon	425952	426049	.	-	.	gene_id "LOC118152095"; transcript_id "XR_004740445.1"; exon_number "2"; exon_id "XR_004740445.1.2"; gene_name "LOC118152095";
> chr1	ncbiRefSeq	exon	428202	428463	.	-	.	gene_id "LOC118152095"; transcript_id "XR_004740445.1"; exon_number "1"; exon_id "XR_004740445.1.1"; gene_name "LOC118152095";
> chr1	ncbiRefSeq	transcript	441590	441696	.	-	.	gene_id "LOC118147983"; transcript_id "XR_004734714.1";  gene_name "LOC118147983";
> chr1	ncbiRefSeq	exon	441590	441696	.	-	.	gene_id "LOC118147983"; transcript_id "XR_004734714.1"; exon_number "1"; exon_id "XR_004734714.1.1"; gene_name "LOC118147983";
> chr1	ncbiRefSeq	transcript	555616	555756	.	+	.	gene_id "LOC118147921"; transcript_id "XR_004734623.1";  gene_name "LOC118147921";
> chr1	ncbiRefSeq	exon	555616	555756	.	+	.	gene_id "LOC118147921"; transcript_id "XR_004734623.1"; exon_number "1"; exon_id "XR_004734623.1.1"; gene_name "LOC118147921";
