### ISSUE TITLE
error . 

### ISSUE THREAD

**Issue by senukobla** [alejandrogzi/gtfsort#6]
I am getting this error with gtfsort - any thoughts on how to fix ? 
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid
thread '<unnamed>' panicked at /Users/apewoksu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtfsort-0.2.1/src/gtf/attr.rs:77:10:
called `Result::unwrap()` on an `Err` value: Invalid

**Comment by alejandrogzi** [comment]
Hi @senukobla,

Thanks for using gtfsort. That error indicates there is a problem with the last column (attributes column). Would you mind to share the gtf file you are trying to sort?

Alejandro

**Comment by IrinaVKuznetsova** [comment]
Hi, 
I am having the same error. What do you need to check at the attribute column?

**Comment by alejandrogzi** [comment]
Hi @IrinaVKuznetsova 

Are you using v.0.2.2? If so, could you do the following to use v.0.3.0 (fixes bugs + faster):

``` bash
git clone https://github.com/alejandrogzi/gtfsort.git && cd gtfsort/gtfsort && cargo build --release
cargo run --release -- -i /path/to/unsorted.gtf -o /path/to/sorted.gtf
```
if the problem persist could you please share your .gtf/.gff to see why is failling?

Best,
Alejandro

**Comment by IrinaVKuznetsova** [comment]
thanks for prompt reply.

Yes, I had v.0.2.2. I've updated with your script, seems to be a version v.0.2.3 not v.0.3.0 is it correct? 
but it worked.
Thanks
